// List of all districts in Sri Lanka
export const sriLankanDistricts = [
  "Ampara",
  "Anuradhapura",
  "Badulla",
  "Batticaloa",
  "Colombo",
  "Galle",
  "Gampaha",
  "Hambantota",
  "Jaffna",
  "Kalutara",
  "Kandy",
  "Kegalle",
  "Kilinochchi",
  "Kurunegala",
  "Mannar",
  "Matale",
  "Matara",
  "Monaragala",
  "Mullaitivu",
  "Nuwara Eliya",
  "Polonnaruwa",
  "Puttalam",
  "Ratnapura",
  "Trincomalee",
  "Vavuniya"
];

// Shipping rates by district (in LKR)
export const districtShippingRates = {
  "Ampara": 350,
  "Anuradhapura": 300,
  "Badulla": 320,
  "Batticaloa": 370,
  "Colombo": 200,
  "Galle": 250,
  "Gampaha": 220,
  "Hambantota": 280,
  "Jaffna": 400,
  "Kalutara": 230,
  "Kandy": 260,
  "Kegalle": 270,
  "Kilinochchi": 390,
  "Kurunegala": 280,
  "Mannar": 380,
  "Matale": 270,
  "Matara": 270,
  "Monaragala": 330,
  "Mullaitivu": 390,
  "Nuwara Eliya": 290,
  "Polonnaruwa": 310,
  "Puttalam": 290,
  "Ratnapura": 260,
  "Trincomalee": 360,
  "Vavuniya": 350
};